(function(h){function f(a,b){if(f.exists(a))throw a+" has configd";var c=b||eval(a);h[a]=c;c=f["@variables"];-1==c.indexOf(a)&&c.push(a)}function s(a){var a=a||this,b="_temp"+Date.now();eval(b+"={value: {}}");eval(b).value=a;return"var "+(e.get(a,"dsl")||Object.keys(a)).map(function(a){return a+"="+b+".value['"+a+"']"}).join(",")+"; delete "+b}function t(a,b){var c={},d;for(d in a)c[d]=b?t(a[d]):a[d];return c}function j(a,b,c){if(!a)return b;var d;if(c&&0<c.length)for(d in a)-1==c.indexOf(d)&&(b[d]=
a[d]);else for(d in a)b[d]=a[d];return b}function m(a,b,c){b=t(b);j(a||{},b,c);return b}function u(a,b,c){var c=m(c,m(a.includeOption,{methodize:!1,context:b,methodizeTo:null,alias:null})),d=c.methodize;Object.keys(a).forEach(function(e){var v=c.alias&&c.alias[e]?c.alias[e]:e;if(!/^__.*__$/.test(e)&&-1==["onIncluded","includeOption"].indexOf(e)){var g=a[e];if(d&&"function"==typeof g){var f=c.context,h=c.methodizeTo;b[v]=function(){f=f||this;var a=[h?h(f):f].concat(Array.prototype.slice.call(arguments,
0));return g.apply(null,a)}}else b[v]=a[e]}});e.has("protocols")&&e.get("protocols").forEach(function(a){w(a,b)});a.onIncluded&&a.onIncluded.call(b,c.context)}function w(a,b){e.has(b,"protocols")||e.set(b,"protocols",[]);var c=e.get(b,"protocols");if(-1==c.indexOf(a)){if(!n(a,b))throw"Not support protocol";c.push(a)}}function p(a,b){var c=function(){var a=c.prototype.initialize;a&&a.apply(this,arguments)};["implement","support","include"].forEach(function(a){c[a]=function(){var b=c.prototype,d=arguments;
b&&i("function",b[a])&&b[a].apply(b,d)}});e.set(c,"config",b,!0);var d=Object.create(a);d.__proto__||e.set(d,"proto",a,!0);var g=b["@statics"];g&&j(g,c);c.extend||(c.extend=z);c.prototype=d;Object.keys(b).filter(function(a){return"@"!=a.charAt(0)&&"constructor"!=a}).forEach(function(a){d[a]=b[a]});e.set(d,"protocols",[]);return c}function i(a,b){if(null===a)return null===b;var c=!1;switch(typeof a){case "string":c=typeof b==a;break;case "object":c=q.isPrototypeOf(a)?n(a,b):a.isPrototypeOf(b);break;
case "function":c=(c=a.prototype)?c.isPrototypeOf(b):b instanceof a}return c}function n(a,b){return e.has(b,"protocols")&&-1!=e.get(b,"protocols").indexOf(a)?!0:a["@base"]&&!n(a["@base"],b)?!1:Object.keys(a).filter(function(a){return"@base"!==a}).every(function(c){return i(Array,a[c])?i("function",b[c]):i(a[c],b[c])})}function x(a){var b=typeof a,c=a;-1==["object","function"].indexOf(b)&&(c=new (eval(b.charAt(0).toUpperCase()+b.slice(1)))(a));return c}function g(a){var b=g.findWrappersByObj(a),a=
x(a);if(0===b.length)return a;var c=new r;b.forEach(function(b){c.include(b.module,m(b.includeOption,{context:a},["context"]))});return c}var k={},e={_parseName:function(a){/^__.*__$/.test(a)||(a="__"+a+"__");return a},has:function(a,b){return a.hasOwnProperty(this._parseName(b))},get:function(a,b){return a[this._parseName(b)]},set:function(a,b,c,d){Object.defineProperty(a,this._parseName(b),{value:c,writable:!0!==d})}};f.exists=function(a){return h.hasOwnProperty?h.hasOwnProperty(a):"undefined"!==
typeof h[a]};f["@variables"]=[];f.del=function(a){var b=f["@variables"].indexOf(objName);if(0<=b){var c=f["@variables"];0===b?c.shift():b==c.length-1?c.pop():f["@variables"]=c.slice(0,b)+c.slice(b+1);h[a]=null;delete h[a];return!0}return!1};f.list=function(){return[].concat(f["@variables"])};f("Mayjs",k);h.global={};f("$run",function(a,b){return a.call(b||{})});var z=function(a){return p(this.prototype,a)},r=p(Object.prototype,{"@statics":{extend:function(a){a.initialize||(a.initialize=function(){this.base()});
return p(this.prototype,a)}},initialize:function(){e.set(this,"protocols",[])},_callerOwner:function(a){var b=null;a:for(var c=function(c){Object.keys(c).forEach(function(d){if(c[d]==a)return b=c,a["@name"]=d,!1});if(b)return!1},d=this;d;){if(!1===c(d))break a;d=d.__proto__}return b},protoMember:function(a){var b=this._callerOwner(arguments.callee.caller);if(b&&(proto=e.get(b,"proto")))return proto[a]},base:function(){var a=arguments.callee.caller,b=this._callerOwner(a),c=a["@name"];delete a["@name"];
c=(a=b?e.get(b,"proto"):null)?a[c]:null;if(i("function",c))return c.apply(this,arguments)},include:function(a,b){u(a,this,b);return this},implement:function(a){w(a,this);return this},supported:function(a){return-1!=this.meta("protocols").indexOf(a)},meta:function(a){return e.get(this,a)},dsl:s}),q=r.extend({initialize:function(a){j(a,this)}}),l=new q({initialize:[],include:[{module:Object},{"[includeOption]":Object}],implement:[q],__protocols__:Array});r.implement(l);e.set(g,"map",{});g.findWrappersByType=
function(a){return e.get(g,"map")[a]||[]};g.findWrappersByPrototype=function(a){for(var b=[],c;a&&!(b=b.concat(g.findWrappersByType(a)),c=a,a=c.prototype||(c.constructor?c.constructor.prototype:null),a==c););return b};g.findWrappersByObj=function(a){if(null===a)return[];var b=[],c=typeof a;"object"==c?(b=b.concat(g.findWrappersByPrototype(a.prototype||a.constructor.prototype)),e.has(a,"protocols")&&e.get(a,"protocols").forEach(function(a){b=b.concat(g.findWrappersByType(a))})):b=b.concat(g.findWrappersByType(c));
return b};g.exists=function(a,b){var c=e.get(g,"map")[a];return!c||1>c.length?!1:0<c.filter(function(a){return a.module==b}).length};g.regist=function(a,b,c){i("function",a)&&(a=a.prototype);if(a&&-1!=["string","object"].indexOf(typeof a)&&"object"==typeof b){var d=e.get(g,"map"),f=d[a];f||(f=d[a]=[]);g.exists(a,b)||f.push({module:b,includeOption:c});return this}};j(g,function(a){var b=g.findWrappersByObj(a),a=x(a);if(0===b.length)return a;b.forEach(function(b){a.include?a.include(b.module,b.includeOption):
u(b.module,a,b.includeOption)});return a});l="$run $fn $parseArray $trace $methodize $module $obj $merge $implement $include $protocol $is $support $dsl $overload $ $$ $enum $global $meta $extend IBase Base Protocol".split(" ");l.forEach(function(a){k[a]=eval(a)});k.dsl=s;e.set(k,"dsl",l.filter(function(a){return"$"===a.charAt(0)}));if(!f.exists("console")){var y={};"info log error debug warn trace dir".split(" ").forEach(function(){y.name=function(){}});f("console",y)}})(this);
