(function(a){if(this.Mayjs)throw"Mayjs has defined";var b=function(b,d){var e=arguments.callee;if(e.exists(b))throw b+" has defined";var f=d||eval(b);a[b]=f;e=e.__variables__;-1==e.indexOf(b)&&e.push(b)};b.exists=function(b){return a.hasOwnProperty?a.hasOwnProperty(b):"undefined"!==typeof a[b]};Object.defineProperty(b,"__variables__",{value:[],writable:!0});b.del=function(b){var d=this.__variables__.indexOf(b);if(0<=d){var e=this.__variables__;0===d?e.shift():d==e.length-1?e.pop():this.__variables__=
e.slice(0,d)+e.slice(d+1);a[b]=null;delete a[b];return!0}return!1};b.list=function(){return[].concat(this.__variables__)};b("Mayjs",{});Mayjs.global=b;"undefined"==typeof console&&(console={},"info log error debug warn trace dir".split(" ").forEach(function(){console.name=function(){}}))})(this);this.Mayjs||(Mayjs={});
Mayjs.util={toObject:function(a){var b=typeof a,c=a;-1==["object","function"].indexOf(b)&&(c=new (eval(b.charAt(0).toUpperCase()+b.slice(1)))(a));return c},parseParamNames:function(a){return(a=a.toString().match(/.*?\((.*)?\)/))&&a[1]?a[1].split(","):[]},run:function(a,b){return a.call(b||{})},fn:function(){return arguments.callee.caller.apply(this,arguments)},parseArray:function(a){return Array.prototype.slice.call(a,0)},trace:function(a,b,c){for(;a;){if(!1===c(a))return!1;a=a[b]}return!0},mix:function(a,
b,c){if(!a)return b;var d;if(c&&0<c.length)for(d in a)-1==c.indexOf(d)&&(b[d]=a[d]);else for(d in a)b[d]=a[d];return b}};this.Mayjs||(Mayjs={});Mayjs.meta={_parseMetaName:function(a){/^__.*__$/.test(a)||(a="__"+a+"__");return a},set:function(a,b,c,d){Object.defineProperty(a,Mayjs.meta._parseMetaName(b),{value:c,writable:!0!==d})},get:function(a,b){return a[Mayjs.meta._parseMetaName(b)]},has:function(a,b){return a.hasOwnProperty(Mayjs.meta._parseMetaName(b))}};
Mayjs.core={"enum":function(a){if("object"==typeof a)return arguments[0];var b={};Mayjs.util.parseArray(arguments).forEach(function(a){b[a]={}});return b},clone:function(a,b){var c={},d;for(d in a)c[d]=b?$clone(a[d]):a[d];return c},methodize:function(a,b,c){return function(){b=b||this;var d=[c?c(b):b].concat(Mayjs.util.parseArray(arguments));return a.apply(null,d)}},merge:function(a,b,c){b=Mayjs.core.clone(b);Mayjs.util.mix(a||{},b,c);return b},safeCall:function(a,b,c,d){if(a&&"function"==typeof a[b])return a[b].apply(d||
a,c)},extend:function(a,b){var c=Mayjs.meta,d=function(){var a=d.prototype.initialize;a&&a.apply(this,arguments)};["implement","support","include"].forEach(function(a){d[a]=function(){Mayjs.core.safeCall(d.prototype,a,arguments)}});c.set(d,"config",b,!0);var e=Object.create(a);e.__proto__||c.set(e,"proto",a,!0);var f=b["@statics"];f&&Mayjs.util.mix(f,d);d.extend||(d.extend=function(a){return Mayjs.core.extend(this.prototype,a)});d.prototype=e;Object.keys(b).filter(function(a){return"@"!=a.charAt(0)&&
"constructor"!=a}).forEach(function(a){e[a]=b[a]});c.set(e,"interfaces",[]);return d},dsl:function(a){var a=a||this,b="_temp"+Date.now();eval(b+"={value: {}}");eval(b).value=a;return"var "+(a.__dsl__||Object.keys(a)).map(function(a){return a+"="+b+".value['"+a+"']"}).join(",")+"; delete "+b}};Mayjs.Interface={};
Mayjs.interface_={_parseArgsMeta:function(a,b){var c=[];if(Mayjs.interface_.is(Array,a)){var d=a.length,e;if(b)for(e=0;e<d;e++)c.push({name:b[e],type:a[e]});else for(e=0;e<d;e+=2)c.push({name:a[e],type:a[e+1]})}else c.push({name:b[0],type:Mayjs.interface_.create(a)});return c},def:function(a,b){Mayjs.meta.set(b,"paramspec",Mayjs.interface_._parseArgsMeta(a,Mayjs.util.parseParamNames(b)));return b},create:function(a,b){var c;if(b){if(!Mayjs.Interface.isPrototypeOf(b))throw"Parameter base is not an Interface";
c=Object.create(b)}else c=Object.create(Mayjs.Interface);Mayjs.util.mix(a,c);return c},is:function(a,b){if(null===a)return null===b;var c=!1;switch(typeof a){case "string":c=typeof b==a;break;case "object":c=Mayjs.Interface.isPrototypeOf(a)?Mayjs.interface_.support(a,b):a.isPrototypeOf(b);break;case "function":c=(c=a.prototype)?c.isPrototypeOf(b):b instanceof a}return c},support:function(a,b){if(Mayjs.meta.has(b,"interfaces")&&-1!=Mayjs.meta.get(b,"interfaces").indexOf(a))return!0;var c=Mayjs.interface_.is,
d;for(d in a)if(c(Array,a[d])){if(!c("function",b[d]))return!1}else if(!c(a[d],b[d]))return!1;return!0},implement:function(a,b){var c=Mayjs.interface_,d=Mayjs.meta;d.has(b,"interfaces")||d.set(b,"interfaces",[]);var e=d.get(b,"interfaces");if(-1==e.indexOf(a)){if(!c.support(a,b))throw"Not support interface_";Object.keys(a).forEach(function(e){c.is(Array,a[e])&&d.set(b[e],"paramspec",c._parseArgsMeta(a[e]))});e.push(a)}},checkParams:function(){for(var a=arguments.callee.caller,b=a.arguments,a=0===
arguments.length?Mayjs.meta.get(a,"paramspec"):Mayjs.interface_._parseArgsMeta(Mayjs.util.parseArray(arguments),Mayjs.util.parseParamNames(a)),c,d=0,e=b.length;d<e;d++){c=a[d].type;if(null===c)break;if(!Mayjs.interface_.is(c,b[d]))return!1}return!0}};
Mayjs.module={create:function(a){return a},include:function(a,b,c){var c=Mayjs.core.merge(c,Mayjs.core.merge(a.includeOption,{methodize:!1,context:b,methodizeTo:null,alias:null})),d=c.methodize;Object.keys(a).forEach(function(e){var f=c.alias&&c.alias[e]?c.alias[e]:e;if(!/^__.*__$/.test(e)&&-1==["onIncluded","includeOption"].indexOf(e)){var g=a[e];b[f]=d&&"function"==typeof g?Mayjs.core.methodize(g,c.context,c.methodizeTo):a[e]}});Mayjs.meta.has("interfaces")&&Mayjs.meta.get("interfaces").forEach(function(a){Mayjs.interface_.implement(a,
b)});a.onIncluded&&a.onIncluded.call(b,c.context)}};Mayjs.IBase=Mayjs.interface_.create({initialize:[],include:["module:",Object,"[includeOption]:",Object],implement:["interface:",Mayjs.interface_.Interface],__interfaces__:Array});
Mayjs.Base=Mayjs.core.extend(Object.prototype,{"@statics":{extend:function(a){a.initialize||(a.initialize=function(){this.base()});return Mayjs.core.extend(this.prototype,a)}},initialize:function(){Mayjs.meta.set(this,"interfaces",[])},_callerOwner:function(a){var b=null;Mayjs.util.trace(this,"__proto__",function(c){Object.keys(c).forEach(function(d){if(c[d]==a)return b=c,a["@name"]=d,!1});if(b)return!1});return b},protoMember:function(a){var b=this._callerOwner(arguments.callee.caller);if(b&&(proto=
Mayjs.meta.get(b,"proto")))return proto[a]},base:function(){var a=arguments.callee.caller,b=this._callerOwner(a),c=a["@name"];delete a["@name"];c=(a=b?Mayjs.meta.get(b,"proto"):null)?a[c]:null;if("function"==typeof c)return c.apply(this,arguments)},include:function(a,b){Mayjs.module.include(a,this,b);return this},implement:function(a){Mayjs.interface_.implement(a,this);return this},supported:function(a){return-1!=this.meta("interfaces").indexOf(a)},meta:function(a){return Mayjs.meta.get(this,a)},
dsl:Mayjs.core.dsl});Mayjs.Base.implement(Mayjs.IBase);Mayjs.$=function(a){var b=arguments.callee.findWrappersByObj(a),a=Mayjs.util.toObject(a);if(0===b.length)return a;var c=new Mayjs.Base;b.forEach(function(b){c.include(b.module,Mayjs.core.merge(b.includeOption,{context:a},["context"]))});return c};Mayjs.meta.set(Mayjs.$,"map",{});
Mayjs.util.mix({findWrappersByType:function(a){return Mayjs.meta.get(Mayjs.$,"map")[a]||[]},findWrappersByPrototype:function(a){for(var b=[],c;a&&!(b=b.concat(this.findWrappersByType(a)),c=a,a=c.prototype||(c.constructor?c.constructor.prototype:null),a==c););return b},findWrappersByObj:function(a){var b=Mayjs.$;if(null===a)return[];var c=[],d=typeof a;"object"==d?(c=c.concat(b.findWrappersByPrototype(a.prototype||a.constructor.prototype)),Mayjs.meta.has(a,"interfaces")&&Maysj.meta.get(a,"interfaces").forEach(function(a){c=
c.concat(b.findWrappersByType(a))})):c=c.concat(b.findWrappersByType(d));return c},exists:function(a,b){var c=Mayjs.meta.get(Mayjs.$,"map")[a];return!c||1>c.length?!1:0<c.filter(function(a){return a.module==b}).length},regist:function(a,b,c){"function"==typeof a&&(a=a.prototype);if(a&&-1!=["string","object"].indexOf(typeof a)&&"object"==typeof b){var d=Mayjs.meta.get(this,"map"),e=d[a];e||(e=d[a]=[]);this.exists(a,b)||e.push({module:b,includeOption:c});return this}}},Mayjs.$);
Mayjs.$$=function(a){var b=Mayjs.$.findWrappersByObj(a),a=Mayjs.util.toObject(a);if(0===b.length)return a;b.forEach(function(b){a.include?a.include(b.module,b.includeOption):Mayjs.module.include(b.module,a,b.includeOption)});return a};
Mayjs.overload={_checkParams:function(a,b){for(var c=a||arguments.callee.caller,d=Mayjs.meta.get(c,"paramspec"),b=b||c.arguments,e=0,f=b.length;e<f;e++){c=d[e].type;if(null===c)break;if(!Mayjs.interface_.is(c,b[e]))return!1}return!0},dispatch:function(a,b){var c=b.length,d=function(a){return Mayjs.meta.get(a,"paramspec")},e=a.filter(function(a){return d(a).length>=c});if(1>=e.length)return e[0];for(var e=e.sort(function(a,b){return d(a).length-d(b).length}),f;f=e.shift();)if(Mayjs.overload._checkParams(f,
b))return f},overload:function(a,b){var c=Mayjs.overload,d=[Mayjs.interface_.def(a,b)],e=function(){var a=arguments,b=c.dispatch(d,a);if(b)return b.apply(this,a)};e.overload=function(a,b){d.push(Mayjs.interface_.def(a,b));return this};return e}};
(function(){Mayjs.dsl=function(){return Mayjs.core.dsl.call(Mayjs.dsl)};var a={obj:function(a){var b=new this.Base;Mayjs.util.mix(a,b);return b},meta:function(a,b){return Mayjs.meta.get(a,b)}};a.global=Mayjs.global;var b=Mayjs.util.mix;b(Mayjs.util,a,["parseParamNames"]);b(Mayjs.core,a);b(Mayjs.module,a,["create"]);a.module=Mayjs.module.create;b(Mayjs.interface_,a,["create","_parseArgsMeta"]);a["interface"]=function(a,b){return Mayjs.interface_.create(a,b)};b(Mayjs.overload,a,["_checkParams"]);var c=
Mayjs.dsl;Object.keys(a).forEach(function(b){c["$"+b]=a[b]});c.$=Mayjs.$;c.$$=Mayjs.$$;Mayjs.global("$run",Mayjs.util.run)})(this);
