(function(a){var e=function(b,c){if(e.defined(b))throw b+" defined";var d=c||eval(b);a[b]=d;d=e.__variables__;-1==d.indexOf(b)&&d.push(b)};e.defined=function(b){return a.hasOwnProperty?a.hasOwnProperty(b):"undefined"!==typeof a[b]};Object.defineProperty(e,"__variables__",{value:[],writable:!0});e.del=function(b){var e=this.__variables__.indexOf(b);if(0<=e){var d=this.__variables__;this.__variables__=d.slice(0,e)+d.slice(e+1)}a[b]=null;delete a[b]};e.list=function(){return[].concat(this.__variables__)};
"undefined"==typeof console&&(console={},"info log error debug warn trace dir".split(" ").forEach(function(){console.name=function(){}}));e("Mayjs",{VERSION:0.5,$global:e,$run:function(b){return 1==arguments.length?b():b.apply(this,Array.prototype.slice.call(arguments,1))},HOST:a,$dsl:function(b){var b=b||this,a="_temp"+Date.now();eval(a+"={value: {}}");eval(a).value=b;return"var "+Object.keys(b).filter(function(a){return b.hasOwnProperty(a)&&"function"==typeof b[a]}).map(function(b){return b+"="+
a+".value['"+b+"']"}).join(",")+"; delete "+a}})})(this);
Mayjs.$run(function(a){a.util={forEach:function(a,b){for(var c in a)if(a.hasOwnProperty(c)&&!/^_/.test(c)&&!1===b(c,a[c]))break},toObject:function(a){var b=typeof a,c=a;-1==["object","function"].indexOf(b)&&(c=new (eval(b.charAt(0).toUpperCase()+b.slice(1)))(a));return c},parseParamNames:function(a){return(a=a.toString().match(/.*?\((.*)?\)/))&&a[1]?a[1].split(","):[]},fn:function(){return arguments.callee.caller.apply(this,arguments)},parseArray:function(a){return Array.prototype.slice.call(a,0)},
trace:function(a,b,c){for(;a;){if(!1===c(a))return!1;a=a[b]}return!0},mix:function(a,b,c){if(!b)return a;var d;if(c&&0<c.length)for(d in b)-1==c.indexOf(d)&&(a[d]=b[d]);else for(d in b)a[d]=b[d];return a},"enum":function(a){if("object"==typeof a)return arguments[0];for(var b={},c=0,d=arguments.length;c<d;c++)b[arguments[c]]={};return b},clone:function(a,b){var c={},d;for(d in a)c[d]=b?$clone(a[d]):a[d];return c},methodize:function(a,b,c){var d=Array.prototype.slice;return function(){var f=b||this,
f=[c?c(f):f].concat(d.call(arguments,0));return a.apply(null,f)}},overwrite:function(e,b,c){var d=e[b].bind(e);e[b]=function(){var b=[d].concat(a.util.parseArray(arguments));return c.apply(e,b)}},merge:function(a,b,c,d){for(var f={},h=null,g,i=0,k=arguments.length;i<k;i++)for(g in h=arguments[i],h)f[g]=h[g];return f}}},Mayjs);
Mayjs.$run(function(a){var e=function(a){/^__.*__$/.test(a)||(a="__"+a+"__");return a};a.meta={set:function(a,c,d,f){Object.defineProperty(a,e(c),{value:d,writable:!0!==f})},get:function(a,c){return a[e(c)]},has:function(a,c){return a.hasOwnProperty(e(c))}}},Mayjs);
Mayjs.$run(function(a){function e(a,d){var f=[];if(c(Array,a))if(d)for(var e=0,g=d.length;e<g;e++)f.push({name:d[e],type:a[e]});else a.forEach(function(a){h.forEach(a,function(a,b){f.push({name:a,type:b});return!1})});else f.push({name:d[0],type:b(a)});return f}function b(a,b){if(b){if(!g.isPrototypeOf(b))throw"Parameter base is not an Interface";interface_=Object.create(b)}else interface_=Object.create(g);h.mix(interface_,a);return interface_}function c(a,b){if(null===a)return null===b;if(void 0===
a)return void 0===b;var c=!1;switch(typeof a){case "string":c=typeof b==a;break;case "object":c=g.isPrototypeOf(a)?d(a,b):a.isPrototypeOf(b);break;case "function":c=(c=a.prototype)?c.isPrototypeOf(b):b instanceof a}return c}function d(a,b){if(f.has(b,"interfaces")&&-1!=f.get(b,"interfaces").indexOf(a))return!0;for(var d in a)if(!/^__.*__$/.test(d))if(c(Array,a[d])){if(!c("function",b[d]))return!1}else if(!c(a[d],b[d]))return!1;return!0}var f=a.meta,h=a.util,g={};a.$interface=b;a.$implement=function(a,
b){f.has(b,"interfaces")||f.set(b,"interfaces",[]);var h=f.get(b,"interfaces");if(-1==h.indexOf(a)){if(!d(a,b))throw"Not support interface";Object.keys(a).forEach(function(d){c(Array,a[d])&&f.set(b[d],"param_types",e(a[d]))});h.push(a)}};a.$support=d;a.$is=c;a.$checkParams=function(){for(var a=arguments.callee.caller,b=a.arguments,a=0===arguments.length?f.get(a,"param_types"):e(h.parseArray(arguments),h.parseParamNames(a)),d,g=0,j=b.length;g<j;g++){d=a[g].type;if(null===d)break;if(!c(d,b[g]))return!1}return!0};
a.util.def=function(a,b){f.set(b,"param_types",e(a,h.parseParamNames(b)));return b};a.Interface=g},Mayjs);
Mayjs.$run(function(a){var e=a.meta,b=a.util;a.$module=function(a){return a};a.$include=function(c,d,f){var f=b.merge({methodize:!1,context:null,methodizeTo:null,alias:null},f),h=f.methodize;b.forEach(c,function(a,c){"onIncluded"!=a&&(d[f.alias&&f.alias[a]?f.alias[a]:a]=h&&"function"==typeof c?b.methodize(c,f.context,f.methodizeTo):c)});e.has("interfaces")&&e.get("interfaces").forEach(function(b){a.$implement(b,d)});c.onIncluded&&c.onIncluded.call(d,f.context)}},Mayjs);
Mayjs.$run(function(a){function e(a,d){var c=Object.create(a),f;Object.__proto__?f=function(){var a=f.prototype.initialize;a&&a.apply(this,arguments)}:(b.set(c,"proto",a,!0),f=function(){this.__proto__=c;var a=f.prototype.initialize;a&&a.apply(this,arguments)});if(!f.extend){var e=arguments.callee;f.extend=function(a){return e(this.prototype,a)}}for(var l in d){var j=d[l];"function"==typeof j&&b.set(j,"name",l);c[l]=j}b.set(c,"interfaces",[]);f.prototype=c;return f}var b=a.meta,c=a.util,d=a.$interface({initialize:[],
base:[],__interfaces__:Array}),f=e(Object.prototype,{initialize:function(){b.set(this,"interfaces",[])},_callerOwner:function(a,d){var f=null;if(d){if(this.__proto__[d]==a)return this.__proto__;c.trace(this,"__proto__",function(b){if(b.hasOwnProperty(d)&&b[d]==a)return f=b,!1})}else c.trace(this,"__proto__",function(d){Object.keys(d).forEach(function(c){if(d[c]==a)return f=d,b.set(a,"name",c),!1})});return f},base:function(){var a=arguments.callee.caller,d=a.name||b.get(a,"name"),c=this._callerOwner(a,
d);d||(d=b.get(a,"name"));d=(a=c?b.get(c,"proto"):null)?a[d]:null;if("function"==typeof d)return d.apply(this,arguments)}});a.$implement(d,f.prototype);f.extend=function(a){var b=e(this.prototype,a);a.initialize||(b.prototype.initialize=function(){this.base()});return b};a.$extend=e;a.Base=f;a.IBase=d;a.$class=function(a){return f.extend(a)};a.$obj=function(a){var b=new f;c.mix(b,a);return b}},Mayjs);
Mayjs.$run(function(a){function e(d){var d=b.toObject(d),c=arguments.callee.findWrappersByObj(d);if(0===c.length)return d;var e={};c.forEach(function(c){a.$include(c.module,e,b.merge({context:d},c.includeOption))});return e}var b=a.util,c=a.meta;c.set(e,"map",[]);b.mix(e,{findWrappersByType:function(a){var b=c.get(e,"map").filter(function(b){return b.type==a});return 0===b.length?[]:b[0].modules},findWrappersByPrototype:function(a){for(var b=[],c;a&&!(b=b.concat(this.findWrappersByType(a)),c=a,a=
c.__proto__||(c.constructor?c.constructor.prototype:null),a==c););return b},findWrappersByObj:function(a){if(null===a)return[];var b=[],h=typeof a;"object"==h||"function"==h?(b=b.concat(e.findWrappersByPrototype(a.__proto__||a.constructor.prototype)),c.has(a,"interfaces")&&Maysj.meta.get(a,"interfaces").forEach(function(a){b=b.concat(e.findWrappersByType(a))})):b=b.concat(e.findWrappersByType(h));return b},exists:function(a,b){return 0<c.get(e,"map").filter(function(b){return b.type==a}).filter(function(a){return a.module==
b}).length},regist:function(a,b,e){if(a!=Function.prototype&&("function"==typeof a&&(a=a.prototype),a!=Function.prototype&&(!a||-1==["string","object"].indexOf(typeof a))))return;if("object"==typeof b){var g=c.get(this,"map"),i=g.filter(function(b){return b.type==a}),e={module:b,includeOption:e};0===i.length?(i={type:a,modules:[e]},g.push(i)):0===i.modules.filter(function(a){return a.module==b}).length&&i.modules.push(e);return this}}});a.$=e;a.$$=function(c){var c=b.toObject(c),f=e.findWrappersByObj(c);
if(0===f.length)return c;f.forEach(function(b){a.$include(b.module,c,b.includeOption)});return c}},Mayjs);
Mayjs.$run(function(a){function e(c,e){for(var h=c||arguments.callee.caller,g=b.get(h,"param_types"),e=e||h.arguments,i=0,k=e.length;i<k;i++){h=g[i].type;if(null===h)break;if(!a.$is(h,e[i]))return!1}return!0}var b=a.meta,c=a.util;a.$overload=function(a,f){var h=["function"==typeof a?a:c.def(paramsTypes,f)],g=function(){var a=arguments,c;a:{c=a;var d=c.length,f=function(a){return b.get(a,"param_types")},g=h.filter(function(a){return f(a).length>=d});if(1>=g.length)c=g[0];else{for(var g=g.sort(function(a,
b){return f(a).length-f(b).length}),m;m=g.shift();)if(e(m,c)){c=m;break a}c=void 0}}if(c)return c.apply(this,a)};g.overload=function(a,b){h.push("function"==typeof a?a:c.def(a,b));return this};return g}},Mayjs);
Mayjs.$run(function(a){var e=a.util;a.dsl={$:a.$,$$:a.$$,$checkParams:a.$checkParams,$class:a.$class,$def:e.def,$enum:e["enum"],$fn:e.fn,$global:a.$global,$interface:a.$interface,$module:a.$module,$run:a.$run,$obj:a.$obj,$is:a.$is,$implement:a.$implement};a.DSL=a.$dsl(a.dsl);a.MFunction=a.$module({overload:function(b,c,d){b=a.$overload(b);b.overload(c,d);return b},paramNames:function(a){return e.parseParamNames(a)},methodize:e.methodize});a.MObject=a.$module({trace:e.trace,clone:e.clone,merge:e.merge,
mix:e.mix,dsl:a.$dsl,meta:a.meta.get,setMeta:a.meta.set,hasMeta:a.meta.has,forEach:e.forEach,support:function(b,c){return a.$support(c,b)},implement:function(b,c){return a.$implement(c,b)},is:function(b,c){return a.$is(c,b)},include:function(b,c,d){return a.$include(c,b,d)},overwrite:e.overwrite});a.init=function(b){b=a.util.merge({injectPrototype:!0},b);b.injectPrototype?(a.$include(a.MObject,Object.prototype,{methodize:!0,context:null}),Object.keys(a.MObject).forEach(function(b){a.HOST[b]=void 0}),
a.$include(a.MFunction,Function.prototype,{methodize:!0,context:null})):(a.$include(a.MObject,a.Base.prototype,{methodize:!0}),a.$.regist(Object,a.MObject,{methodize:!0}),a.$.regist(Function,a.MFunction,{methodize:!0}))}},Mayjs);
