(function(a){var b=function(c,d){if(b.defined(c))throw c+" defined";var f=d||eval(c);a[c]=f;f=b.__variables__;-1==f.indexOf(c)&&f.push(c)};b.defined=function(c){return a.hasOwnProperty?a.hasOwnProperty(c):"undefined"!==typeof a[c]};Object.defineProperty(b,"__variables__",{value:[],writable:!0});b.del=function(c){var b=this.__variables__.indexOf(c);if(0<=b){var f=this.__variables__;this.__variables__=f.slice(0,b)+f.slice(b+1)}a[c]=null;delete a[c]};b.list=function(){return[].concat(this.__variables__)};
"undefined"==typeof console&&(console={},"info log error debug warn trace dir".split(" ").forEach(function(){console.name=function(){}}));b("Mayjs",{VERSION:0.5,$global:b,$run:function(a){return 1==arguments.length?a():a.apply(this,Array.prototype.slice.call(arguments,1))},HOST:a,$dsl:function(a){var a=a||this,b="_temp"+Date.now();eval(b+"={value: {}}");eval(b).value=a;return"var "+Object.keys(a).filter(function(b){return a.hasOwnProperty(b)&&"function"==typeof a[b]}).map(function(a){return a+"="+
b+".value['"+a+"']"}).join(",")+"; delete "+b}})})(this);
Mayjs.util=Mayjs.$run(function(){return{toObject:function(a){var b=typeof a,c=a;-1==["object","function"].indexOf(b)&&(c=new (eval(b.charAt(0).toUpperCase()+b.slice(1)))(a));return c},parseParamNames:function(a){return(a=a.toString().match(/.*?\((.*)?\)/))&&a[1]?a[1].split(","):[]},fn:function(){return arguments.callee.caller.apply(this,arguments)},parseArray:function(a){return Array.prototype.slice.call(a,0)},trace:function(a,b,c){for(;a;){if(!1===c(a))return!1;a=a[b]}return!0},mix:function(a,b,
c){if(!b)return a;var d;if(c&&0<c.length)for(d in b)-1==c.indexOf(d)&&(a[d]=b[d]);else for(d in b)a[d]=b[d];return a},"enum":function(a){if("object"==typeof a)return arguments[0];for(var b={},c=0,d=arguments.length;c<d;c++)b[arguments[c]]={};return b},clone:function(a,b){var c={},d;for(d in a)c[d]=b?$clone(a[d]):a[d];return c},methodize:function(a,b,c){var d=Array.prototype.slice;return function(){var f=b||this,f=[c?c(f):f].concat(d.call(arguments,0));return a.apply(null,f)}},merge:function(a,b,c,
d){for(var f={},e=null,h,g=0,i=arguments.length;g<i;g++)for(h in e=arguments[g],e)f[h]=e[h];return f}}},Mayjs);Mayjs.meta=Mayjs.$run(function(){var a=function(a){/^__.*__$/.test(a)||(a="__"+a+"__");return a};return{set:function(b,c,d,f){Object.defineProperty(b,a(c),{value:d,writable:!0!==f})},get:function(b,c){return b[a(c)]},has:function(b,c){return b.hasOwnProperty(a(c))}}});
Mayjs.$run(function(a){function b(a,b){var f=[];if(d(Array,a)){var h=a.length,e;if(b)for(e=0;e<h;e++)f.push({name:b[e],type:a[e]});else for(e=0;e<h;e+=2)f.push({name:a[e],type:a[e+1]})}else f.push({name:b[0],type:c(a)});return f}function c(a,b){if(b){if(!g.isPrototypeOf(b))throw"Parameter base is not an Interface";interface_=Object.create(b)}else interface_=Object.create(g);h.mix(interface_,a);return interface_}function d(a,b){if(null===a)return null===b;if(void 0===a)return void 0===b;var c=!1;switch(typeof a){case "string":c=
typeof b==a;break;case "object":c=g.isPrototypeOf(a)?f(a,b):a.isPrototypeOf(b);break;case "function":c=(c=a.prototype)?c.isPrototypeOf(b):b instanceof a}return c}function f(a,b){if(e.has(b,"interfaces")&&-1!=e.get(b,"interfaces").indexOf(a))return!0;for(var c in a)if(!/^__.*__$/.test(c))if(d(Array,a[c])){if(!d("function",b[c]))return!1}else if(!d(a[c],b[c]))return!1;return!0}var e=a.meta,h=a.util,g={};a.$interface=c;a.$implement=function(a,c){e.has(c,"interfaces")||e.set(c,"interfaces",[]);var h=
e.get(c,"interfaces");if(-1==h.indexOf(a)){if(!f(a,c))throw"Not support interface";Object.keys(a).forEach(function(f){d(Array,a[f])&&e.set(c[f],"param_types",b(a[f]))});h.push(a)}};a.$support=f;a.$is=d;a.$checkParams=function(){for(var a=arguments.callee.caller,c=a.arguments,a=0===arguments.length?e.get(a,"param_types"):b(h.parseArray(arguments),h.parseParamNames(a)),f,g=0,j=c.length;g<j;g++){f=a[g].type;if(null===f)break;if(!d(f,c[g]))return!1}return!0};a.util.def=function(a,c){e.set(c,"param_types",
b(a,h.parseParamNames(c)));return c};a.Interface=g},Mayjs);
Mayjs.$run(function(a){var b=a.meta,c=a.util;a.$module=function(a){return a};a.$include=function(d,f,e){var e=c.merge({methodize:!1,context:null,methodizeTo:null,alias:null},e),h=e.methodize;Object.keys(d).forEach(function(a){var b=e.alias&&e.alias[a]?e.alias[a]:a;if(!/^__.*__$/.test(a)&&"onIncluded"!=a){var k=d[a];f[b]=h&&"function"==typeof k?c.methodize(k,e.context,e.methodizeTo):d[a]}});b.has("interfaces")&&b.get("interfaces").forEach(function(c){a.$implement(c,f)});d.onIncluded&&d.onIncluded.call(f,
e.context)}},Mayjs);
Mayjs.$run(function(a){function b(a,b){var f=Object.create(a),e;Object.__proto__?e=function(){var a=e.prototype.initialize;a&&a.apply(this,arguments)}:(c.set(f,"proto",a,!0),e=function(){this.__proto__=f;var a=e.prototype.initialize;a&&a.apply(this,arguments)});if(!e.extend){var d=arguments.callee;e.extend=function(a){return d(this.prototype,a)}}for(var l in b){var j=b[l];"function"==typeof j&&c.set(j,"name",l);f[l]=j}c.set(f,"interfaces",[]);e.prototype=f;return e}var c=a.meta,d=a.util,f=a.$interface({initialize:[],
__interfaces__:Array}),e=b(Object.prototype,{initialize:function(){c.set(this,"interfaces",[])},_callerOwner:function(a,b){var f=null;if(b){if(this.__proto__[b]==a)return this.__proto__;d.trace(this,"__proto__",function(c){if(c.hasOwnProperty(b)&&c[b]==a)return f=c,!1})}else d.trace(this,"__proto__",function(b){Object.keys(b).forEach(function(e){if(b[e]==a)return f=b,c.set(a,"name",e),!1})});return f},base:function(){var a=arguments.callee.caller,b=a.name||c.get(a,"name"),f=this._callerOwner(a,b);
b||(b=c.get(a,"name"));b=(a=f?c.get(f,"proto"):null)?a[b]:null;if("function"==typeof b)return b.apply(this,arguments)}});a.$implement(f,e.prototype);e.extend=function(a){var c=b(this.prototype,a);a.initialize||(c.prototype.initialize=function(){this.base()});return c};a.$extend=b;a.Base=e;a.IBase=f;a.$class=function(a){return e.extend(a)};a.$obj=function(a){var b=new e;d.mix(b,a);return b}},Mayjs);
Mayjs.$run(function(a){function b(b){var b=c.toObject(b),e=arguments.callee.findWrappersByObj(b);if(0===e.length)return b;var d={};e.forEach(function(e){a.$include(e.module,d,c.merge({context:b},e.includeOption))});return d}var c=a.util,d=a.meta;d.set(b,"map",[]);c.mix(b,{findWrappersByType:function(a){var c=d.get(b,"map").filter(function(b){return b.type==a});return 0===c.length?[]:c[0].modules},findWrappersByPrototype:function(a){for(var b=[],c;a&&!(b=b.concat(this.findWrappersByType(a)),c=a,a=
c.__proto__||(c.constructor?c.constructor.prototype:null),a==c););return b},findWrappersByObj:function(a){if(null===a)return[];var c=[],h=typeof a;"object"==h||"function"==h?(c=c.concat(b.findWrappersByPrototype(a.__proto__||a.constructor.prototype)),d.has(a,"interfaces")&&Maysj.meta.get(a,"interfaces").forEach(function(a){c=c.concat(b.findWrappersByType(a))})):c=c.concat(b.findWrappersByType(h));return c},exists:function(a,c){return 0<d.get(b,"map").filter(function(b){return b.type==a}).filter(function(a){return a.module==
c}).length},regist:function(a,b,c){if(a!=Function.prototype&&("function"==typeof a&&(a=a.prototype),a!=Function.prototype&&(!a||-1==["string","object"].indexOf(typeof a))))return;if("object"==typeof b){var g=d.get(this,"map"),i=g.filter(function(b){return b.type==a}),c={module:b,includeOption:c};0===i.length?(i={type:a,modules:[c]},g.push(i)):0===i.modules.filter(function(a){return a.module==b}).length&&i.modules.push(c);return this}}});a.$=b;a.$$=function(f){var f=c.toObject(f),e=b.findWrappersByObj(f);
if(0===e.length)return f;e.forEach(function(b){a.$include(b.module,f,b.includeOption)});return f}},Mayjs);
Mayjs.$run(function(a){function b(b,e){for(var d=b||arguments.callee.caller,g=c.get(d,"param_types"),e=e||d.arguments,i=0,k=e.length;i<k;i++){d=g[i].type;if(null===d)break;if(!a.$is(d,e[i]))return!1}return!0}var c=a.meta,d=a.util;a.$overload=function(a,e){var h=[d.def(a,e)],g=function(){var a=arguments,d;a:{d=a;var e=d.length,f=function(a){return c.get(a,"param_types")},g=h.filter(function(a){return f(a).length>=e});if(1>=g.length)d=g[0];else{for(var g=g.sort(function(a,b){return f(a).length-f(b).length}),
m;m=g.shift();)if(b(m,d)){d=m;break a}d=void 0}}if(d)return d.apply(this,a)};g.overload||(g.overload=function(a,b){h.push(d.def(a,b));return this});return g}},Mayjs);
Mayjs.$run(function(a){var b=a.util;a.dsl={$:a.$,$$:a.$$,$checkParams:a.$checkParams,$class:a.$class,$def:b.def,$enum:b["enum"],$fn:b.fn,$global:a.$global,$interface:a.$interface,$module:a.$module,$run:a.$run,$obj:a.$obj};a.DSL=a.$dsl(a.dsl);a.MFunction=a.$module({overload:function(b,d){return a.$overload(d,b)},paramNames:function(a){return b.parseParamNames(a)},methodize:b.methodize});a.MObject=a.$module({trace:b.trace,clone:b.clone,merge:b.merge,mix:b.mix,dsl:a.$dsl,meta:a.meta.get,setMeta:a.meta.set,
hasMeta:a.meta.has,support:function(b,d){return a.$support(d,b)},implement:function(b,d){return a.$implement(d,b)},is:function(b,d){return a.$is(d,b)},include:function(b,d,f){return a.$include(d,b,f)}});a.init=function(b){b=a.util.merge({injectPrototype:!0},b);b.injectPrototype?(a.$include(a.MObject,Object.prototype,{methodize:!0,context:null}),Object.keys(a.MObject).forEach(function(b){a.HOST[b]=void 0}),a.$include(a.MFunction,Function.prototype,{methodize:!0,context:null})):(a.$include(a.MObject,
a.Base.prototype,{methodize:!0}),a.$.regist(Object,a.MObject,{methodize:!0}),a.$.regist(Function,a.MFunction,{methodize:!0}))}},Mayjs);
