(function(g){function f(a,b){if(f.exists(a))throw a+" has defined";var c=b||eval(a);g[a]=c;c=f["@variables"];-1==c.indexOf(a)&&c.push(a)}function m(a){var a=a||this,b="_temp"+Date.now();eval(b+"={value: {}}");eval(b).value=a;return"var "+(a.__dsl__||Object.keys(a)).map(function(a){return a+"="+b+".value['"+a+"']"}).join(",")+"; delete "+b}function n(a,b){var c={},d;for(d in a)c[d]=b?n(a[d]):a[d];return c}function i(a,b,c){if(!a)return b;var d;if(c&&0<c.length)for(d in a)c.indexOf(d)||(b[d]=a[d]);
else for(d in a)b[d]=a[d];return b}function p(a,b,c){b=n(b);i(a,b,c);return b}function q(a,b,c){var c=p(c,{methodize:!1,context:b}),d=c.methodize;Object.keys(a).forEach(function(c){if(!/^__.*__$/.test(c)&&"onIncluded"!==c){var e=a[c];b[c]=d&&"function"==typeof e?function(){var a=[this].concat(arguments);return e.apply(null,a)}:a[c]}});a.__protocols__&&a.__protocols__.forEach(function(a){r(a,b)});a.onIncluded&&a.onIncluded.call(b,c.context)}function r(a,b){b.__protocols__||Object.defineProperty(b,
"__protocols__",{value:[],writable:!0});var c=b.__protocols__;-1==c.indexOf(a)&&l(a,b)&&c.push(a)}function s(a){var b=a["@base"]||(a["@base"]=h);delete a["@base"];var c=Object.create(b);c.__proto__||Object.defineProperty(c,"__proto__",{value:b});i(a,c);Object.defineProperty(c,"__protocols__",{value:[],writable:!0});return c}function t(a,b){if(a===b)return!0;if(null===a)return null===b;var c=!1;switch(typeof a){case "string":c=typeof b==a;break;case "object":c=u.isPrototypeOf(a)?l(a,b):a.isPrototypeOf(b);
break;case "function":c=(c=a.prototype)?c.isPrototypeOf(b):b instanceof a}return c}function l(a,b){if(b.__protocols__&&-1!=b.__protocols__.indexOf(a))return!0;if(a["@base"]&&!l(a["@base"],b))return!1;Object.keys(b).filter(function(a){return"@base"!==a}).forEach(function(c){if(!t(a[c],b[c]))return!1});return!0}function v(a){var b=typeof a,c=a;-1==["object","function"].indexOf(b)&&(c=new (eval(b.charAt(0).toUpperCase()+b.slice(1)))(a));return c}function e(a){var b=e.findWrappersByObj(a),a=v(a);if(0===
b.length)return a;var c=h.create();b.forEach(function(b){c.include(b.module,p(b.includeOption,{context:a},["context"]))});return c}var j={};f.exists=function(a){return g.hasOwnProperty?g.hasOwnProperty(a):"undefined"!==typeof g[a]};f["@variables"]=[];f.del=function(a){var b=f["@variables"].indexOf(objName);if(0<=b){var c=f["@variables"];0===b?c.shift():b==c.length-1?c.pop():f["@variables"]=c.slice(0,b)+c.slice(b+1);g[a]=null;delete g[a];return!0}return!1};f.list=function(){return[].concat(f["@variables"])};
f("Pure",j);g.global={};f("$run",function(a,b){return a.call(b||{})});var h={initialize:function(){Object.defineProperty(this,"__protocols__",{value:[],writable:!0})},callerOwner:function(a){var b=null;a:for(var c=function(c){Object.keys(c).forEach(function(d){if(c[d]==a)return b=c,a["@name"]=d,!1});if(b)return!1},d=this;d;){if(!1===c(d))break a;d=d.__proto__}return b},proto:function(){var a=this.callerOwner(arguments.callee.caller);if(a)return a.__proto__},base:function(){var a=arguments.callee.caller,
b=this.callerOwner(a),c=a["@name"];delete a["@name"];if(b&&b.__proto__&&t("function",b.__proto__[c]))return b.__proto__[c].apply(this,arguments)},create:function(){var a=Object.create(this);h.initialize.call(a);a.__proto__||Object.defineProperty(a,"__proto__",{value:this});this.initialize&&this.initialize.apply(a,arguments);return a},include:function(a,b){q(a,this,b);return this},implement:function(a){r(a,this);return this},supported:function(a){return-1!=this.__protocols__.indexOf(a)},dsl:m,"@base":Object.prototype},
h=s(h),u=s({initialize:function(a){i(a,this)}}),k=u.create({initialize:Function,create:Function,include:Function,implement:Function,prototype:Object,__protocols__:Array});h.implement(k);e.__map__={};e.findWrappersByType=function(a){return e.__map__[a]||[]};e.findWrappersByPrototype=function(a){for(var b=[],c;a&&!(b=b.concat(e.findWrappersByType(a)),c=a,a=c.prototype||(c.constructor?c.constructor.prototype:null),a==c););return b};e.findWrappersByObj=function(a){if(null===a)return[];var b=[],c=typeof a;
"object"==c?(b=b.concat(e.findWrappersByPrototype(a.prototype||a.constructor.prototype)),a.__protocols__&&a.__protocols__.forEach(function(a){b=b.concat(e.findWrappersByType(a))})):b=b.concat(e.findWrappersByType(c));return b};e.exists=function(a,b){var c=e.__map__[a];return!c||1>c.length?!1:0<c.filter(function(a){return a.module==b}).length};e.regist=function(a,b,c){if(a&&-1!=["string","object"].indexOf(typeof a)&&"object"==typeof b){var d=e.__map__[a];d||(d=e.__map__[a]=[]);e.exists(a,b)||d.push({module:b,
includeOption:c});return this}};i(e,function(a){var b=e.findWrappersByObj(a),a=v(a);if(0===b.length)return a;b.forEach(function(b){a.include?a.include(b.module,b.includeOption):q(b.module,a,b.includeOption)});return a});k="$run $fn $parseArray $trace $methodize $module $proto $obj $merge $implement $include $protocol $is $support $dsl $overload $ $$ $enum $global IBase Base Protocol".split(" ");k.forEach(function(a){j[a]=eval(a)});j.dsl=m;Object.defineProperty(j,"__dsl__",{value:k.filter(function(a){return"$"===
a.charAt(0)}),writable:!0});if(!f.exists("console")){var w={};"info log error debug warn trace dir ".split(" ").forEach(function(){w.name=function(){}});f("console",w)}})(this);
